# Generated by Django 2.2 on 2019-04-19 04:45

from django.db import migrations, models
import djongo.models.fields
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', djongo.models.fields.EmbeddedModelField(model_container=polls.models.Post, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
